export const AUTH_SIGN_IN_WITH_GOOGLE_CHANNEL = 'auth:sign-in-with-google'
export const DASHBOARD_SNAPSHOT_CHANNEL = 'dashboard:get-snapshot'
export const STORAGE_SNAPSHOT_CHANNEL = 'storage:get-snapshot'
export const STORAGE_SAVE_SERVER_CONFIG_CHANNEL = 'storage:save-server-config'
export const SERVER_SETUP_LIST_VANILLA_VERSIONS_CHANNEL = 'serverSetup:list-vanilla-versions'
export const SERVER_SETUP_SETUP_VANILLA_SERVER_CHANNEL = 'serverSetup:setup-vanilla-server'
